# Generated by Django 2.2 on 2020-05-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_playerhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='club_state',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
